name-template: '=BTC= co@30 Hearts & Minds v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
exclude-lables:
    - 'ignore changelog'
change-template: '- $TITLE (@$AUTHOR).'

template: |
    Requires [ACE3](https://steamcommunity.com/workshop/filedetails/?id=463939057).

    _[Optionals :](https://github.com/Vdauphin/HeartsAndMinds/files/5147451/All.Hearts.and.Minds.mods.html.zip)_
    - [CUP units and vehicles mod](https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/), [Community Factions Project](https://steamcommunity.com/workshop/filedetails/?id=1369691841),
    - [RHS USAF](http://www.rhsmods.org/), [RHS AFRF](http://www.rhsmods.org/), [RHS GREF](http://www.rhsmods.org/), [RHS SAF](http://www.rhsmods.org/),
    - [RDS A2 Civilian Pack mod](https://forums.bistudio.com/topic/170165-rds-a2-civilian-pack/),
    - [3CB Factions](https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286), [Project OPFOR](https://forums.bistudio.com/topic/193185-project-opfor/), [Iraqi-Syrian Conflic](https://forums.bohemia.net/forums/topic/179746-iraqi-syrian-conflict/), [Central African Rebels [SFF-R]](https://steamcommunity.com/sharedfiles/filedetails/?id=879843800),
    - [FAP Units (Foes & Allies Pack)](https://steamcommunity.com/sharedfiles/filedetails/?id=656514091), [VETERAN](https://steamcommunity.com/workshop/filedetails/?id=1774055232), [GLOBAL MOBILIZATION - COLD WAR GERMANY CDLC](https://store.steampowered.com/app/1042220/Arma_3_Creator_DLC_Global_Mobilization__Cold_War_Germany/)
    - [Taliban Fighters by EricJ](https://steamcommunity.com/sharedfiles/filedetails/?id=668919514),
    - [The Unsung Vietnam War Mod](https://steamcommunity.com/workshop/filedetails/?id=943001311), [S.O.G. PRAIRIE FIRE CDLC](https://store.steampowered.com/app/1227700/Arma_3_Creator_DLC_SOG_Prairie_Fire/)
    - [Iron Front 3 Lite](https://steamcommunity.com/sharedfiles/filedetails/?id=878977835), [Face of War WW2](https://steamcommunity.com/sharedfiles/filedetails/?id=891433622),
    - [Operation: TREBUCHET](https://steamcommunity.com/sharedfiles/filedetails/?id=769440155), [Operation: TREBUCHET First Contact](https://steamcommunity.com/workshop/filedetails/?id=1572627279), [OPCAN - OPTRE Reskin Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2016312756).

    [Changelog](https://github.com/Vdauphin/HeartsAndMinds/milestone/68?closed=1):

    - Mission.sqm/Param.hpp not changed.
    $CHANGES